// Generated by ReScript, PLEASE EDIT WITH CARE


function UIUtils$RenderIf(Props) {
  var children = Props.children;
  var condition = Props.condition;
  if (condition) {
    return children;
  } else {
    return null;
  }
}

var RenderIf = {
  make: UIUtils$RenderIf
};

export {
  RenderIf ,
}
/* No side effect */
