// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ButtonsDemo$DashboardComponentsLibrary from "./demo/ButtonsDemo.bs.js";

function App(Props) {
  return React.createElement(ButtonsDemo$DashboardComponentsLibrary.make, {});
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
