// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button$DashboardComponentsLibrary from "./components/Button.bs.js";

import './index.css'
;

require("./index.css")
;

import "tailwindcss/tailwind.css"
;

var Button = Button$DashboardComponentsLibrary.make;

export {
  Button ,
}
/*  Not a pure module */
